[workspace]
members = ["aura", "aura-core", "aura-node-lib", "aura-wallet-lib"]

resolver = "2" # Recommended


[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"
